In [19]:
%load_ext autoreload

In [157]:
%autoreload

import numpy as np
import physics as phys
import utilities as utils
import spectrum as spec

from scipy import integrate

In [114]:
eng = np.array([0.1, 2, 4.5, 10, 367, 4250])
dNdE = np.array([0.004, 0.3, 500, 28, 1e-5, 1e7])
rs = 200
test_spec = spec.Spectrum(eng,dNdE,rs)

In [87]:
print(np.log(test_spec.eng))
print(test_spec.log_bin_width)
print(np.log(test_spec.bin_boundary))

[-2.30258509  0.69314718  1.5040774   2.30258509  5.90536185  8.35467426]
[ 2.99573227  1.90333124  0.80471896  2.20064223  3.02604458  2.44931241]
[-3.80045123 -0.80471896  1.09861229  1.90333124  4.10397347  7.13001805
  9.57933047]


In [88]:
print(test_spec.totN())
print(np.dot(test_spec.eng*test_spec.log_bin_width,test_spec.dNdE))
print(test_spec.toteng())
print(np.dot(test_spec.eng**2*test_spec.log_bin_width,test_spec.dNdE))

print(test_spec.totN('bin',np.array([1.5,4.5])))
print(test_spec.toteng('bin',np.array([1.5,6.5])))

104095780017.0
104095780017.0
4.42407054768e+14
4.42407054768e+14
2427.37402683
4.42407054768e+14


In [90]:
np.log(spec.get_bin_bound(eng))

array([-3.80045123, -0.80471896,  1.09861229,  1.90333124,  4.10397347,
        7.13001805,  9.57933047])

In [129]:
test_spec_CMB = phys.CMB_spec(1.,1)
print(test_spec_CMB)

7.6744358165e+12


In [158]:
def CMB_spec_at1eV(eng):
    return phys.CMB_spec(eng,1)
    
test = spec.discretize(CMB_spec_at1eV,np.array([0.1,0.2,1,40]))
print(test.dNdE)

[  1.32320934e+12   3.29409682e+12   4.98139772e+12   5.23894085e+09]


In [120]:
print(a[0])

IndexError: too many indices for array