In [5]:
%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [21]:
%autoreload

import numpy as np
import physics as phys
import utilities as utils
import spectrum as spec

from scipy import integrate

In [27]:
def CMB_spec_at1eV(eng):
    return phys.CMB_spec(eng,1)
    
eng_test = np.array([0.1, 1.2, 36.54, 230.122, 510])
test = spec.Spectrum(eng_test, np.array([10., 15.2, 16.7, 1302.29, 0.1]), 1000.)
init_toteng = test.toteng()
print('initial total N: ', test.totN())
print('initial total eng: ', test.toteng())
print('initial abscissa: ', test.eng)
print('initial dN/dE: ', test.dNdE)
print('initial N in each bin: ', test.totN('bin', np.array([0,1,2,3,4])))
print('initial eng in each bin: ', test.toteng('bin', np.array([0,1,2,3,4])))
test.rebin(np.array([0.3, 5, 50, 210.4, 3050]))
test.rebin(np.array([0.1, 0.52, 5, 210.4, 4012]))
print('**********************************************************')
# test.redshift(20)
print('final total N: ', test.totN())
print('final total eng: ', test.toteng())
print('final total eng/initial total eng: ', test.toteng()/init_toteng)
print('final abscissa: ', test.eng)
print('final dN/dE: ', test.dNdE)
print('final N in each bin: ', test.totN('bin', np.array([0,1,2,3,4])))
print('final eng in each bin: ', test.toteng('bin', np.array([0,1,2,3,4])))
print('N underflow: ', test.underflow['N'])
print('eng underflow: ', test.underflow['eng'])
print('**********************************************************')
test.redshift(5)
print('final total N: ', test.totN())
print('final total eng: ', test.toteng())
print('final total eng/initial total eng: ', test.toteng()/init_toteng)
print('final abscissa: ', test.eng)
print('final dN/dE: ', test.dNdE)
print('final N in each bin: ', test.totN('bin', np.array([0,1,2,3,4])))
print('final eng in each bin: ', test.toteng('bin', np.array([0,1,2,3,4])))
print('N underflow: ', test.underflow['N'])
print('eng underflow: ', test.underflow['eng'])
print('**********************************************************')
test.redshift(2.975)
print('final total N: ', test.totN())
print('final total eng: ', test.toteng())
print('final total eng/initial total eng: ', test.toteng()/init_toteng)
print('final abscissa: ', test.eng)
print('final dN/dE: ', test.dNdE)
print('final N in each bin: ', test.totN('bin', np.array([0,1,2,3,4])))
print('final eng in each bin: ', test.toteng('bin', np.array([0,1,2,3,4])))
print('N underflow: ', test.underflow['N'])
print('eng underflow: ', test.underflow['eng'])

initial total N:  396686.697945
initial total eng:  90974348.553
initial abscissa:  [  1.00000000e-01   1.20000000e+00   3.65400000e+01   2.30122000e+02
   5.10000000e+02]
initial dN/dE:  [  1.00000000e+01   1.52000000e+01   1.67000000e+01   1.30229000e+03
   1.00000000e-01]
initial N in each bin:  [  2.48490665e+00   5.38170529e+01   1.60374079e+03   3.94986069e+05]
initial eng in each bin:  [  2.48490665e-01   6.45804635e+01   5.86006884e+04   9.08949842e+07]
**********************************************************
final total N:  396686.697945
final total eng:  90974348.553
final total eng/initial total eng:  1.0
final abscissa:  [  1.00000000e-01   5.20000000e-01   5.00000000e+00   2.10400000e+02
   4.01200000e+03]
final dN/dE:  [  1.40540352e+02   2.07092487e+01   9.11410742e+01   5.58920148e+02
   1.73520256e-01]
final N in each bin:  [  2.31703064e+01   2.10639149e+01   1.36778530e+03   3.93220603e+05]
final eng in each bin:  [  2.31703064e+00   1.09532358e+01   6.83892652e+03

In [264]:
print(2302.58509*(100-50)/(500-50))
print(2302.58509*(500-100)/(500-50))
print(2.30258509*(1-0.88888889))
print(2.30258509*(0.88888889))

255.84278777777777
2046.7423022222222
0.2558427852193498
2.04674230478065


In [215]:
eng = np.array([0.1, 2, 4.5, 10, 367, 4250])
dNdE = np.array([0.004, 0.3, 500, 28, 1e-5, 1e7])
rs = 200
test_spec = spec.Spectrum(eng,dNdE,rs)

N_in_bin = test_spec.totN('bin',np.array([0, 1, 2, 3, 4, 5, 6]))
eng_in_bin = test_spec.toteng('bin',np.array([0, 1, 2, 3, 4, 5, 6]))
print(N_in_bin)
print(test_spec.totN())
print(np.sum(N_in_bin))

print(eng_in_bin)
print(test_spec.toteng())
print(np.sum(eng_in_bin))

[  1.19829291e-03   1.14199875e+00   1.81061765e+03   6.16179823e+02
   1.11055836e-02   1.04095778e+11]
104095780017.0
104095780017.0
[  1.19829291e-04   2.28399749e+00   8.14777943e+03   6.16179823e+03
   4.07574919e+00   4.42407055e+14]
4.42407054768e+14
4.42407054768e+14


In [69]:
eng = np.array([0.1, 2, 4.5, 10, 367, 4250])
dNdE = np.array([0.004, 0.3, 500, 28, 1e-5, 1e7])
rs = 200
test_spec = spec.Spectrum(eng,dNdE,rs)

In [70]:
print(np.log(test_spec.eng))
print(test_spec.log_bin_width)
print(np.log(test_spec.bin_boundary))

[-2.30258509  0.69314718  1.5040774   2.30258509  5.90536185  8.35467426]
[ 2.99573227  1.90333124  0.80471896  2.20064223  3.02604458  2.44931241]
[-3.80045123 -0.80471896  1.09861229  1.90333124  4.10397347  7.13001805
  9.57933047]


In [151]:
print(test_spec.totN())
print(np.dot(test_spec.eng*test_spec.log_bin_width,test_spec.dNdE))
print(test_spec.toteng())
print(np.dot(test_spec.eng**2*test_spec.log_bin_width,test_spec.dNdE))



104095780017.0
104095780017.0
4.42407054768e+14
4.42407054768e+14


In [83]:
print(test_spec.totN('bin',np.array([1.5,2.5,3.5])))
print(test_spec.toteng('bin',np.array([1.5,6.5])))

What 0
905.879825118
4.42407054768e+14


In [129]:
test_spec_CMB = phys.CMB_spec(1.,1)
print(test_spec_CMB)

7.6744358165e+12


In [40]:
p = np.where(np.array([1,2,3,4]) < 0)
print(p.size)

AttributeError: 'tuple' object has no attribute 'size'

In [23]:
a = np.where((np.array([1,2,3,4,5]) > 3) | (np.array([1,2,3,4,5]) < 5), np.ones(5), np.zeros(5))
print(a)
b = np.where((np.array([1,2,3,4,5]) > 3) | (np.array([1,2,3,4,5]) < 5))
print(b)

[ 1.  1.  1.  1.  1.]
(array([0, 1, 2, 3, 4]),)


In [18]:
print(a[np.array([2,2,2])])

[ 0.  0.  0.]


In [172]:
print(np.insert(a,0,3))

[ 3.  1.  1.  0.  0.  0.]


In [ ]:
print(a[np])